### ISSUE TITLE
Post CRUD hooks should be awaited

### ISSUE THREAD

**Issue by chris-steele** [adapt-security/adapt-authoring-api#16]
### What happened?

The code awaits the outcome of the `pre-` hooks, but not the `post-` hooks. I think it would be useful/safe not to respond to the request until the `post-` hooks have completed. This way clients would have an accurate way of determining when the operation has completed (e.g. when determining when to show and hide a loading popup).

### Expected behaviour

See above

### Steps to reproduce

N/A

### Authoring tool version

v1

**Comment by taylortom** [comment]
Yep, sounds reasonable to me
